Flag to get either the accepted changes or the original text
Keystone-Strategy/docx2python pull request #2
Opened 2023-10-02 17:01 UTC by deayalar

2023-10-02 20:59 UTC, sebassdc requested changes

2023-10-02 20:59 UTC, sebassdc commented on docx2python/docx_text.py
> +                branches(branch, is_inserted or False)
You don't need the or False in here

2023-10-03 00:12 UTC, bholligan commented
Can you add a little more clarity on how you plan on using the "only_deleted" argument to empower the end goal of notifying the user which sections were deleted and then using the playbook to tell them whether that's acceptable?

2023-10-03 00:17 UTC, bholligan commented
What should happen when the following combination of flags occurs?
- is_deleted (True) & accepted_changes (False)

2023-10-03 15:29 UTC, deayalar commented on docx2python/docx_text.py
> +                branches(branch, is_inserted or False)
done!

2023-10-03 21:40 UTC, deayalar commented
@bholligan 
I changed the flags by a parameter that can take three values "accepted", "original" or "deleted"

2023-10-05 15:35 UTC, bholligan approved these changes
lgtm

2023-10-05 16:06 UTC, merged